sudo: false

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - language: node_js
      node_js:
        - '10.16'
      before_script:
        - yarn install --non-interactive --no-progress --ignore-scripts
      script:
        - yarn lint
        - yarn test:coverage
